<a href="https://colab.research.google.com/github/JuHyeon-S/20-1-Image_Processing/blob/master/%EC%98%81%EC%83%81%EC%B2%98%EB%A6%AC_3%EC%A3%BC%EC%B0%A8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#3주차 실습

-> Numpy 라이브러리

###Numpy
- 행렬, 다차원 배열, 벡터 등을 쉽게 처리할 수 있도롥 지원하는 Python 라이브러리
- 데이터 구조 외에도 수치 계산을 위해 효율적으로 구현된 기능을 제공함
- ndarray는 Numpy의 핵심인 다차원 행렬 자료구조 클래스이며 모든 요소는 같은 자료형 이어야 함

- pip install numpy을 이용하여 numpy 라이브러리를 설치할수 있음
>  Jupyter Notebook에는 이미 설치되어 있음

In [1]:
pip install numpy

In [3]:
import numpy as np      # np라는 명칭으로 지정하여 사용함

# 리스트를 이용하여 배열 생성
print("--------------------------")
list1 = [0, 1, 2, 3, 4]
arr1 = np.array(list1)
print('arr1')
print('{}\n'.format(arr1))
print('배열 자료형: {}'.format(type(arr1)))
print('배열 형태:{}, 배열 차원: {}'.format(arr1.shape, arr1.ndim))

print("--------------------------")
arr2 = np.array([5, 6, 7, 8, 9, 10])
print('arr2')
print('{}\n'.format(arr2))
print('배열 형태:{}, 배열 차원: {}'.format(arr2.shape, arr2.ndim))

print("--------------------------")
arr3 = np.array([[1, 3, 5], [2, 4, 6], [7, 8, 9]])
print('arr3')
print('{}\n'.format(arr3))
print('배열 형태:{}, 배열 차원: {}'.format(arr3.shape, arr3.ndim))

--------------------------
arr1
[0 1 2 3 4]

배열 자료형: <class 'numpy.ndarray'>
배열 형태:(5,), 배열 차원: 1
--------------------------
arr2
[ 5  6  7  8  9 10]

배열 형태:(6,), 배열 차원: 1
--------------------------
arr3
[[1 3 5]
 [2 4 6]
 [7 8 9]]

배열 형태:(3, 3), 배열 차원: 2


In [4]:
import numpy as np

print('zeros()를 이용한 배열 생성\n')

# zeros
print('-----------------------------------------------------')
arr_zeros_1 = np.zeros(5)
print('크기가 5인 1차원 배열')
print('{}\n'.format(arr_zeros_1))
print('자료형: {}'.format(arr_zeros_1.dtype))

print('-----------------------------------------------------')
arr_zeros_2 = np.zeros((2, 3))
print('2개의 행과 3개의 열로 이루어진 2차원 배열')
print('{}\n'.format(arr_zeros_2))
print('자료형: {}'.format(arr_zeros_2.dtype))

print('-----------------------------------------------------')
arr_zeros_3 = np.zeros((5, 2))
print('5개의 행과 2개의 열로 이루어진 2차원 배열')
print('{}\n'.format(arr_zeros_3))
print('자료형: {}'.format(arr_zeros_3.dtype))

zeros()를 이용한 배열 생성

-----------------------------------------------------
크기가 5인 1차원 배열
[0. 0. 0. 0. 0.]

자료형: float64
-----------------------------------------------------
2개의 행과 3개의 열로 이루어진 2차원 배열
[[0. 0. 0.]
 [0. 0. 0.]]

자료형: float64
-----------------------------------------------------
5개의 행과 2개의 열로 이루어진 2차원 배열
[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]

자료형: float64


#3주차 과제

## 과제 1번

- 1부터 50까지의 요소를 가지는 배열을 생성하시오.
- 배열 요소 중 홀수와 짝수를 분류하여 배열로 저장하시오,
> 단, for문과 if문 사용하지 않음
- 홀수 배열과 짝수 배열을 전치 변환하시오,
- 전치 변환한 홀수 배열과 짝수 배열을 행렬 곱 연산을 수행하시오.

In [1]:
import numpy as np        # numpy 라이브러리를 np라는 명칭으로 사용한다.

# 1~50까지의 배열 생성
arr = np.arange(1,51)
print("1 ~ 50까지의 요소를 가지는 배열 생성\n{}\n".format(arr))

# 홀수 짝수 분류
oddarr = arr[np.where(arr%2 != 0)].reshape(5,5)       # np.where 로 홀수 찾아 5x5로 형태 변환한다.
evenarr = arr[np.where(arr%2 == 0)].reshape(5,5)      # np.where 로 짝수 찾아 5x5로 형태 변환한다.
print("배열 요소중 홀수인 값\n{}\n".format(oddarr))
print("배열 요소중 짝수인 값\n{}\n".format(evenarr))

oddarr2 = oddarr.T                                    # T 함수로 배열을 전치 변환한다.
evenarr2 = evenarr.T
print("홀수 배열을 전치 변환\n{}\n".format(oddarr2))
print("짝수 배열을 전치 변환\n{}\n".format(evenarr2))

# 행렬 곱을 연산하는 dot 함수를 사용하여 계산한다.
print("\n전치 변환한 홀수 배열과 짝수 배열의 행렬 곱 연산\n{}".format(np.dot(oddarr2, evenarr2)))

1 ~ 50까지의 요소를 가지는 배열 생성
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50]

배열 요소중 홀수인 값
[[ 1  3  5  7  9]
 [11 13 15 17 19]
 [21 23 25 27 29]
 [31 33 35 37 39]
 [41 43 45 47 49]]

배열 요소중 짝수인 값
[[ 2  4  6  8 10]
 [12 14 16 18 20]
 [22 24 26 28 30]
 [32 34 36 38 40]
 [42 44 46 48 50]]

홀수 배열을 전치 변환
[[ 1 11 21 31 41]
 [ 3 13 23 33 43]
 [ 5 15 25 35 45]
 [ 7 17 27 37 47]
 [ 9 19 29 39 49]]

짝수 배열을 전치 변환
[[ 2 12 22 32 42]
 [ 4 14 24 34 44]
 [ 6 16 26 36 46]
 [ 8 18 28 38 48]
 [10 20 30 40 50]]


전치 변환한 홀수 배열과 짝수 배열의 행렬 곱 연산
[[ 830 1880 2930 3980 5030]
 [ 890 2040 3190 4340 5490]
 [ 950 2200 3450 4700 5950]
 [1010 2360 3710 5060 6410]
 [1070 2520 3970 5420 6870]]


##과제 2번
#### 두 배열이 있을 때, 아래의 문제들을 해결하시오
- 첫 번째 배열 = [1, 2, 3, 5, 3, 4, 3, 6, 9, 7, 0, 8, 7, 10]
- 두 번째 배열 = [7, 2, 10, 5, 7, 4, 9, 1, 9, 8, 0, 3, 7, 6]

######1) 두 배열에 모두 존재하는 요소와 색인 위치를 반환하시오
- 단, for 문과 if 문 사용하지 않음
- 결과
> 두 배열에 모두 존재하는 요소: [2 5  4 9 0 7]
>
> 두 배열에 존재하는 요소의 색인 위치: (array([1, 3, 5, 8, 10, 12]),)

######2) 반환된 배열을 다음과 형태로 변형하시오
- 결과
> 배열 형태 변형
>
> [[2 5 4] [9 0 7]]




In [2]:
import numpy as np

# np.array 함수로 배열을 선언한다.(np.where 사용을 위해)
arr1 = np.array([1, 2, 3, 5, 3, 4, 3, 6, 9, 7, 0, 8, 7, 10])
arr2 = np.array([7, 2, 10, 5, 7, 4, 9, 1, 9, 8, 0, 3, 7, 6])

# np.where 함수로 arr1과 arr2에 모두 존재하는 요소를 찾아 arr3에 저장
# 배열이름[np.where()] -> 요소 반환 / np.where() -> 위치 반환
arr3 = arr1[np.where(arr1 == arr2)]

print("두 배열에 모두 존재하는 요소: {}".format(arr3))
print("두 배열에 모두 존재하는 요소의 색인 위치: {}".format(np.where(arr1 == arr2)))

# 배열의 형태를 2x3 으로 변형한다.
arr3 = arr3.reshape(2, 3)
print("\n배열 형태 변형\n{}".format(arr3))

# np.max() / np.min() -> 최댓값 / 최솟값 요소
# np.argmax() / np.argmin() -> 최댓값 / 최솟값 색인 위치
# axis >>  0 이면 열 기준  /  1 이면 행 기준
print("\n열(Column)을 기준으로\n배열의 최댓값: {}, 최댓값의 색인 위치: {}".format(np.max(arr3, axis = 0), np.argmax(arr3, axis = 0)))
print("\n행(Row)을 기준으로\n배열의 최솟값: {}, 최솟값의 색인 위치: {}".format(np.min(arr3, axis = 1), np.argmin(arr3, axis = 1)))

두 배열에 모두 존재하는 요소: [2 5 4 9 0 7]
두 배열에 모두 존재하는 요소의 색인 위치: (array([ 1,  3,  5,  8, 10, 12]),)

배열 형태 변형
[[2 5 4]
 [9 0 7]]

열(Column)을 기준으로
배열의 최댓값: [9 5 7], 최댓값의 색인 위치: [1 0 1]

행(Row)을 기준으로
배열의 최솟값: [2 0], 최솟값의 색인 위치: [0 1]
